---
title: "Data Driven CV"
author: "Will Ball"
date: "27/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install & Load Packages

Devtools & DataDrivenCV from github

```{r packages}
library(devtools)
devtools::install_github("nstrayer/datadrivencv")
library(datadrivencv)
library(readxl)
```

## Create .csv files for storing data

Function creates 4x csv files in 'Data' folder

```{r convert}
use_csv_data_storage()
```

## Build CV

Add information to csv files above, then build CV using main function

```{r cv}
datadrivencv::use_datadriven_cv(
  full_name = "William Ball",
  data_location = "https://docs.google.com/spreadsheets/d/1bPybtMYFqQnBpJ1R332Mx_2AXP0S2-nPeozlFtufvoo/edit?usp=sharing",
  pdf_location = "https://github.com/will-ball/CV/pdf/ball_cv.pdf",
  html_location = "wpball.com/CV",
  source_location = "https://github.com/will-ball/CV"
)
```

## Render

Render in HTML -> knit cv.Rmd

Render in PDF -> run render_cv.R
